#%RAML 1.0 NamedExample
value: 
  -
   productId: 100
   price: 100
   productName: test product
   productType: eclectroniocs
   unerwarraenty: true
   manufactureDetails:
    companyname: test pvt ltd
    companylocation: mubai
    

  -
   productId: 101
   price: 200
   productName: test 1 product
   productType: eclectroniocs gadeges
   unerwarraenty: true
   manufactureDetails:
    companyname: test pvt ltd mangalore
    companylocation: bangalore
   



